btc_oneshot: Enhance safety and features
* Use `exec` for running bitcoind so that signals are properly passed
  through and to save minor resources by taking over proces and not
  forking as well as passing return value back up.
* Exit on failure, and print commands that run for logging.
* Indent is four spaces (blame markdown...).
* Allow the default command line arguments to be overriden if passed in.

diff --git a/bin/btc_oneshot b/bin/btc_oneshot
--- a/bin/btc_oneshot
+++ b/bin/btc_oneshot
@@ -1,9 +1,19 @@
 #!/bin/bash
 
-chown 1000:1000 /bitcoin
-btc_init # generate bitcoin.conf
+set -ex
+
+# Generate bitcoin.conf
+btc_init
+
 if [ ! -d /bitcoin/.bitcoin/blocks ]; then
-  btc_bootstrap
+    # Download via bittorrent file, fail quietly
+    btc_bootstrap || true
 fi
 
-bitcoind -rpcallowip=*
+if [ $# -gt 0 ]; then
+    args=("$@")
+else
+    args=("-rpcallowip=*")
+fi
+
+exec bitcoind "${args[@]}"
